import type { PortfolioProject } from '@/types/portfolio';

export const projects = [
  {
    id: '01',
    title: 'OpsCore',
    category: 'SaaS Platform',
    description:
      'A multi-tenant SaaS platform focused on workspace management, RBAC, billing, and production-style architecture with a premium product experience.',
    image: '/project/opscore.jpg',
    tech: [
      'Next.js',
      'PostgreSQL',
      'TypeScript',
      'shadcn/ui',
      'GSAP',
      'Node.js',
      'Express.js',
      'Postgresql',
      'Prisma',
      'Better Auth',
      'Stripe',
    ],
    date: '2026-04',
    status: 'live',
    liveUrl: 'https://opscore-frontend.vercel.app',
    repositoryUrls: [
      { label: 'Frontend', url: 'https://github.com/ArnabSaga/OpsCore-Frontend' },
      { label: 'Backend', url: 'https://github.com/ArnabSaga/OpsCore-Backend' },
    ],
    access: ['USER', 'SUPER_ADMIN'],
    workspaceAccess: ['OWNER', 'ADMIN', 'MEMBER'],
  },
  {
    id: '02',
    title: 'Medi-Store',
    category: 'Fullstack Platform',
    description:
      'A medicine commerce platform with admin workflow, inventory logic, secure checkout flow, and a clean, scalable fullstack architecture.',
    image: '/project/medistore.jpg',
    tech: [
      'Next.js',
      'PostgreSQL',
      'TypeScript',
      'shadcn/ui',
      'Node.js',
      'Express.js',
      'Postgresql',
      'Prisma',
      'Better Auth',
    ],
    date: '2026-01',
    status: 'live',
    liveUrl: 'https://medi-store-frontend-puce.vercel.app',
    repositoryUrls: [
      { label: 'Frontend', url: 'https://github.com/ArnabSaga/MediStore-Frontend' },
      { label: 'Backend', url: 'https://github.com/ArnabSaga/MediStore-Backend' },
    ],
    access: ['CUSTOMER', 'SELLER', 'ADMIN'],
  },
  {
    id: '03',
    title: 'Awwer',
    category: 'Gaming Platform',
    description:
      'An interactive gaming-focused experience with expressive motion, bold visual rhythm, and a playful interface structure.',
    image: '/project/awwer.jpg',
    tech: ['React', 'JavaScript', 'GSAP', 'Tailwind'],
    date: '2025-07',
    status: 'live',
    liveUrl: 'https://awwer.vercel.app',
    repositoryUrls: [{ label: 'Repository', url: 'https://github.com/ArnabSaga/Awwer' }],
    contribution: 'Frontend',
  },
  {
    id: '04',
    title: 'Velvet-Pour',
    category: 'E-Commerce',
    description:
      'A luxury retail experience centered on mood, storytelling, and refined transitions for a more sensory web interaction.',
    image: '/project/velvet-pour.jpg',
    tech: ['React', 'JavaScript', 'GSAP'],
    date: '2025-07',
    status: 'live',
    liveUrl: 'https://velvet-pour-gamma-nine.vercel.app',
    repositoryUrls: [{ label: 'Repository', url: 'https://github.com/ArnabSaga/Velvet-Pour' }],
    contribution: 'Frontend',
  },
  {
    id: '05',
    title: 'MeetAI',
    category: 'AI Platform',
    description:
      'An AI-first concept platform designed for intelligent meeting workflows, assistant-driven productivity, and future-facing UI.',
    image: '/project/meetai.jpg',
    tech: ['Next.js', 'TypeScript', 'TRPC', 'PostgreSQL', 'Drizzle ORM'],
    date: '2025-07',
    status: 'in-progress',
    repositoryUrls: [{ label: 'Repository', url: 'https://github.com/ArnabSaga/MeetAi' }],
  },
  {
    id: '06',
    title: 'Monster-Steamer',
    category: 'E-Commerce',
    description: 'Premium carpet cleaning and professional hygiene services in San Diego.',
    image: '/project/monster-steamer.png',
    tech: ['React', 'JavaScript', 'GSAP'],
    date: '2024-06',
    status: 'live',
    liveUrl: 'https://monster-steamer-inky.vercel.app/',
    repositoryUrls: [{ label: 'Repository', url: 'https://github.com/ArnabSaga/Monster-Steamer' }],
    contribution: 'Frontend',
  },
  {
    id: '07',
    title: 'Rik-Dental-Care',
    category: 'Healthcare-Platform',
    description:
      'Rik-Dental-Care will be a modern bilingual dental-care platform for a doctor-owned clinic. The main goal is to build brand value, patient trust, smooth appointment booking, medical history management, prescription/invoice delivery, and AI-based patient assistance.',
    image: '/project/rik-dental-care.png',
    tech: [
      'Next.js',
      'PostgreSQL',
      'TypeScript',
      'shadcn/ui',
      'Node.js',
      'Express.js',
      'PostgreSQL',
      'Prisma',
      'Better Auth',
    ],
    date: '2024-06',
    status: 'in-progress',
    repositoryUrls: [
      { label: 'Frontend', url: 'https://github.com/Sumyta-Bentey-Habib/Rik-Dental-Care' },
      { label: 'Backend', url: 'https://github.com/ArnabSaga/Rik-Dental-Care-Backend' },
    ],
    access: ['MANAGER', 'PATIENT', 'DENTIST'],
  },
  {
    id: '08',
    title: 'Operix',
    category: 'SaaS Platform',
    description:
      'A production grade NestJS backend for replacing spreadsheet driven operations with secure workflows, audit trails, analytics, file evidence, Excel migration, and Team scoped inventory.',
    image: '/project/operix.png',
    tech: [
      'Next.js',
      'PostgreSQL',
      'TypeScript',
      'shadcn/ui',
      'Node.js',
      'Nest.js',
      'Postgresql',
      'Prisma',
    ],
    date: '2026-08',
    status: 'in-progress',
    repositoryUrls: [
      { label: 'Frontend', url: 'https://github.com/ArnabSaga/Operix-Frontend' },
      { label: 'Backend', url: 'https://github.com/ArnabSaga/Operix-Backend' },
    ],
    access: ['SUPER_ADMIN', 'ADMIN', 'MEMBER'],
  },
  {
    id: '09',
    title: 'Neoxra',
    category: 'Social Media and Professional Community Platform',
    description:
      'Neoxra is a social media and professional community platform designed to connect individuals through shared interests, professional growth, and meaningful interactions. It combines the features of a modern social network with the structure of a professional community hub, providing tools for networking, collaboration, and knowledge sharing.',
    image: '/project/nexora.png',
    tech: [
      'Next.js',
      'TypeScript',
      'shadcn/ui',
      'Node.js',
      'Express.js',
      'Postgresql',
      'Prisma',
      'Better Auth',
    ],
    date: '2026-05',
    status: 'in-progress',
    repositoryUrls: [
      { label: 'Frontend', url: 'https://github.com/ArnabSaga/Neoxra-Frontend' },
      { label: 'Backend', url: 'https://github.com/ArnabSaga/Nexora-Backend' },
    ],
    access: ['USER', 'MODERATOR', 'ADMIN', 'SUPER_ADMIN'],
  },
] as const satisfies readonly PortfolioProject[];
